#%RAML 1.0 ResourceType

traits:
  businessTraits: /traits/business-trait.raml
  clientIdsecret: /traits/client-id-secret-traits.raml
  transactionId: /traits/transaction-id.raml 

types:
  errorResponseDataType: /dataTypes/error-response-data-Type.raml 
