#%RAML 1.0 Trait
headers:
  x-client-Id:
    description: Client ID enforcement policy is enforced on this System API as this API is  consumed for internal purposes. The Client Secret should be passed as a header by the consumer of this API.
    required: true
    type: string
    example: "kjfdksh8w47ryt487te4t"
  x-client-secret:
    description: Client ID enforcement policy is enforced on this System API as this API is consumed for internal purposes. The Client Secret should be passed as a header by the consumer of this API.
    required: true
    type: string
    example: " jhdfjhvdfj38748763we87"
      
